<?php `id` mediumint(7) unsigned NOT NULL auto_increment,
               `parent` mediumint(7) unsigned NOT NULL,
               `timestamp` int(20) NOT NULL,
               `bumped` int(20) NOT NULL,
               `ip` varchar(15) NOT NULL,
               `name` varchar(75) NOT NULL,
               `tripcode` varchar(10) NOT NULL,
               `email` varchar(75) NOT NULL,
               `nameblock` varchar(255) NOT NULL,
               `subject` varchar(75) NOT NULL,
               `message` text NOT NULL,
               `password` varchar(255) NOT NULL,
               `file` varchar(75) NOT NULL,
               `file_hex` varchar(75) NOT NULL,
               `file_original` varchar(255) NOT NULL,
               `file_size` int(20) unsigned NOT NULL default '0',
               `file_size_formatted` varchar(75) NOT NULL,
               `image_width` smallint(5) unsigned NOT NULL default '0',
               `image_height` smallint(5) unsigned NOT NULL default '0',
               `thumb` varchar(255) NOT NULL,
               `thumb_width` smallint(5) unsigned NOT NULL default '0',
               `thumb_height` smallint(5) unsigned NOT NULL default '0',
?>